services:
  postgres:
    image: postgres:16-alpine
    container_name: secureops-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: secureops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7-jammy
    container_name: secureops-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: secureops_archive
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data:
